os: linux
dist: xenial
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: COVERAGE_FLAGS="--coverage-clover coverage/clover.xml"

install:
  - composer self-update
  - composer update --prefer-dist --no-progress --no-suggest --optimize-autoloader $COMPOSER_FLAGS

script: vendor/bin/phpunit $COVERAGE_FLAGS
